### ISSUE TITLE
Detecting end-of-file

### ISSUE THREAD

**Issue by stevedonovan** [GeertJohan/go.linenoise#2]
Thanks BTW for a most useful binding!  It would be useful if we could detect that the user has closed stdin with ctrl-D or wants to escape with ctrl-C.  Both of these make the original `linenoise` function return `NULL`.  But Go strings are not nil-able; there is no way to tell difference between user pressing empty line and user having cancelled the session with these keys. 

Now 1st prize is not breaking the existing API, so I thought one could represent 'end-of-input/session' with a special string. One I tried was "\000" which has length 1 (this is not C ;)) and where `s[0]==0`.

Another solution is to extend the API and have a `linenoise.LineBytes` (or whatever, I'm not talented at naming things) which returns a `[]byte` value, which can be easily converted into a string and _is_ nil-able.

Thoughts?  Otherwise people are going to be frustrated if they can't get out of a session with the usual keys and have to kill the terminal......

**Comment by GeertJohan** [comment]
Auch.. This is indeed a bit of a problem..
Up until now I just handled the "quit" command in my terminal applications.. But I can surely see the problem here.. ctrl+C would also be nice in my applications..

I've just now tried to catch the signal using signal.Notify() from the standard library. but that doesn't seem to work when "inside" a linenoise.Line() call...

I'd rather not use magic or 'unique' values in a string to indicate a ctrl+C.. This is not very Go-like.

It is possible to change the linenoise.Line() layout to return an error as second return value, which then return somethin like linenoise.KillError on ctrl+C. Codewise this is the most elegant solution I can see... However, as you say, it breaks existing API, which is nasty.. On the other hand, this is probably something that a lot of people are missing.. I'd rather consider this a bug then a missing feature. Therefore, changing the API could suffice..

Thoughts?

**Comment by GeertJohan** [comment]
I've added this functionality in the (expirimental) branch ctrlc.
https://github.com/GeertJohan/go.linenoise/blob/ctrlc/linenoise.go#L17

**Comment by stevedonovan** [comment]
Thanks, that works well and is exactly the 'Go way' of handling this issue. (Also allows for other kinds of error checking)   I cannot be the only one who uses ctrl-C/ctrl-D without thinking.....

So, it looks like you are going to have break people's programs ;)  However, easy error to detect and fix!

**Comment by GeertJohan** [comment]
ctrlc branch was merged by pull request 4. This issue is done.
